### ISSUE TITLE
Helper Function imgix() throws error

### ISSUE THREAD

**Issue by hasnatbabur** [Otisz/Laravel-Imgix#11]
Using latest 'Laravel-Imgix' version on PHP 7.3.

\Imgix::createUrl() method working fine.

But using imgix() helper method with same parameter throws following errors.

`
Illuminate\Contracts\Container\BindingResolutionException: Unresolvable dependency resolving [Parameter #0 [ <required> $domain ]] in class Imgix\UrlBuilder
`

**Comment by Otisz** [comment]
Thank you for reporting this bug.
Now, this has been fixed and released.
